[project]
name = "llm-twin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dmitry", email = "dimonpd@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4",
    "chromedriver-autoinstaller",
    "click",
    "datasets",
    "fake-useragent",
    "fastapi",
    "graphviz>=0.21",
    "html2text",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "jinja2",
    "jmespath",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "loguru",
    "numpy",
    "opik",
    "polars",
    "pymongo",
    "qdrant-client",
    "requests",
    "rich",
    "selenium",
    "sentence-transformers",
    "tiktoken",
    "torch",
    "trl>=0.24.0",
    "unsloth>=2026.8.9",
    "uvicorn",
    "webdriver-manager",
    "zenml[local,server]",
]

[project.scripts]
llm-twin = "llm_twin:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
